server: 
  port: ${server.port}
spring:
  application: 
    name: eureka-consumer
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appName: coumser
    instanceId: ${eureka.instance.appName}-port:${server.port}
    lease-renewal-interval-in-seconds: 1 
    lease-expiration-duration-in-seconds: 2
consumer-client:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule