server:
  port: 8110

spring:
  application:
    name: ctx-middle-transaction-producer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appName: ${spring.application.name}
    instanceId: ${eureka.instance.appName}-port:${server.port}
    lease-renewal-interval-in-seconds: 1 
    lease-expiration-duration-in-seconds: 2
    
ctx-middle-transaction-producer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
