server: 
  port: ${server.port}
spring:
  application: 
    name: transaction-consumer
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appName: ${spring.application.name} # 当设置appName后，服务名称以这个为准，会覆盖Spring.application.name，
    instanceId: ${eureka.instance.appName}-port:${server.port}
    lease-renewal-interval-in-seconds: 1 
    lease-expiration-duration-in-seconds: 2
    
transaction-consumer:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule