server:
  port: 8111

spring:
  application:
    name: ctx-middle-order-producer

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appName: ${spring.application.name}
    instanceId: ${eureka.instance.appName}-port:${server.port}
    lease-renewal-interval-in-seconds: 1 
    lease-expiration-duration-in-seconds: 2
